### ISSUE TITLE
Version 6 release date.

### ISSUE THREAD

**Issue by adrorocker** [orchestral/canvas#12]
I'm developing a Laravel ^8.x package so I wanted to use this package as part of my test suite. I was gonna contribute with a PR to support that version of Laravel, but I noticed you already have version 6 in the making which support the version of laravel I'm using. Do you have a ETA for version 6?

**Comment by crynobone** [comment]
Will do it later today, I haven't checked if there any missing stubs that we should add for the release.

**Comment by adrorocker** [comment]
That is just awesome 🤘 . Let me know if you need help with anything. Thanks.

**Comment by crynobone** [comment]
Done.
