### ISSUE TITLE
Support anonymous classes when creating migration.

### ISSUE THREAD

**Issue by abishekrsrikaanth** [orchestral/canvas#16]
Can you add support for anonymous classes when creating migration as described here https://laravel.com/docs/8.x/migrations#anonymous-migrations

**Comment by crynobone** [comment]
On 6.x, publish the stub and customize it.

**Comment by abishekrsrikaanth** [comment]
@crynobone Is there a canvas command to publish the stubs? Also, will these stubs remain in the package you are developing or is this something that can be setup globally?

**Comment by crynobone** [comment]
`./vendor/bin/canvas stub:publish` and it's per package.

**Comment by abishekrsrikaanth** [comment]
Thank you. Appreciate the help. Probably needs to be documented on the README file.
