### ISSUE TITLE
Command "make:seeder" is not defined.

### ISSUE THREAD

**Issue by sosupp** [orchestral/canvas#18]
- Package Version: 7.4.0
- Laravel Version: #.#.#
- PHP Version: ^8.0

### Description:
Running the command "make:seeder" results in the error attached as a screenshot.

### Steps To Reproduce:
run the command: composer exec canvas make:seeder YourSeeder
![seeder_cmd_error](https://user-images.githubusercontent.com/20490921/213862077-acc0c44a-fb1d-4afb-97fa-2e6b9907a997.jpg)

### Possible Solution
Add an entry for the $app->add() for Seeder. See attach screenshot

![seeder_cmd_solution](https://user-images.githubusercontent.com/20490921/213862082-8102ecb6-3994-4d43-b9dd-41a5686be005.jpg)

**Comment by crynobone** [comment]
You can add it on your project `canvas.yaml`:

https://github.com/orchestral/canvas/blob/d1b37c8bd9dc1372317af17d0a1877e2b18d4052/canvas.yaml#L20-L22
