### ISSUE TITLE
When running nova:action the files go into the vendor folder

### ISSUE THREAD

**Issue by jaymeh** [orchestral/canvas#34]
- Package Version: 8.11.6
- Laravel Version: 10.43.0
- PHP Version: 8.2.13

### Description:
Similar to this issue #32, running a command on a package to make "Actions" and "Repeatables" (haven't tested the other nova types so this could also affect those). The outputted files get put into: `/vendor/orchestra/testbench-core/laravel/app/Nova/Actions`

### Steps To Reproduce:
Create a new package in Laravel [I'm using this skeleton by Spatie](https://github.com/spatie/package-skeleton-laravel) and require canvas.
1. Run vendor/bin/canvas preset package to generate a canvas.yml file.
2. Run the vendor/bin/canvas nova:action TestAction command.
3. The generated view file goes inside the `/vendor/orchestra/testbench-core/laravel/app/Nova/Actions` folder rather than the packages `src/Nova/Actions` folder.

**Comment by crynobone** [comment]
Canvas doesn't provide replacement for custom generators.
