### ISSUE TITLE
When running make:xxx command, generated file goes to vendor. 

### ISSUE THREAD

**Issue by thunder809** [orchestral/canvas#35]
- Package Version: 9.0.1
- Laravel Version: 11.1.0
- PHP Version: 8.3.4

### Description:
We use https://github.com/Jeroen-G/laravel-packager for package development.

All make:### commands put the generated result into the vendor folder.

I have not testet every single make-command, but all I tested did not work for me.

Example: 
vendor/bin/canvas make:model TestModel 

outputs to: ./vendor/orchestra/testbench-core/laravel/app/Models/TestModel.php
but should go to ./src/Models/TestModel.php

### Steps To Reproduce:
1. Create a new package in laravel. We use laravel-packager with this skeleton:  https://www.robin-rick.de/laravel11-package-skeleton.zip
`php artisan package:new some-vendor some-package-name --skeleton="https://www.robin-rick.de/laravel11-package-skeleton.zip"`
2. run `vendor/bin/canvas preset package` (with namespace argument) to generate canvas.yaml
3. run `vendor/bin/canvas make:model TestModel`
4. The generated view file goes inside the vendor folder rather than the packages resources folder.

**Comment by crynobone** [comment]
Fixed in https://github.com/orchestral/canvas/releases/tag/v9.0.2
